apiVersion: carto.run/v1alpha1
kind: Deliverable
metadata:
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/component: deliverable
    app.kubernetes.io/part-of: tanzu-java-web-app
    app.tanzu.vmware.com/deliverable-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    carto.run/cluster-template-name: external-deliverable-template
    carto.run/resource-name: deliverable
    carto.run/supply-chain-name: source-test-scan-to-url
    carto.run/template-kind: ClusterTemplate
    carto.run/template-lifecycle: mutable
    carto.run/workload-name: tanzu-java-web-app
    carto.run/workload-namespace: dev
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-java-web-app
  name: tanzu-java-web-app
  namespace: dev
spec:
  params:
  - name: gitops_ssh_secret
    value: git-https
  source:
    git:
      ref:
        branch: staging
      url: https://gitlab.ho-test.com/shjeon/gitops-tap.git
    subPath: config/dev/tanzu-java-web-app
