apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/max-scale: "10"
    autoscaling.knative.dev/metric: concurrency
    autoscaling.knative.dev/minScale: "3"
    autoscaling.knative.dev/target: "20"
    autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
    autoscaling.knative.dev/enable-scale-to-zero: "true"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.name: tanzu-java-web-app
  name: tanzu-java-web-app
  namespace: dev
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17.*
  env:
  - name: LC_ALL
    value: C.UTF-8
  - name: JAVA_TOOL_OPTIONS
    value: -Dmanagement.endpoint.health.probes.add-additional-paths=true -Dmanagement.endpoint.health.show-details=always
      -Dmanagement.endpoints.web.base-path=/actuator -Dmanagement.endpoints.web.exposure.include=*
      -Dmanagement.health.probes.enabled=true -Dmanagement.server.port=8081 -Dserver.port=8080
      -Dserver.shutdown.grace-period=24s
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      description: A set of API endpoints to manage the resources within the petclinic
        app.
      location:
        baseURL: https://petstore3.huntedhappy.kro.kr
        path: /api/v3/openapi.json
      owner: default-team
      system: tanzu
      type: openapi
  - name: scanning_source_policy
    value: sample-scan-policy
  - name: scanning_image_policy
    value: sample-scan-policy
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: maven
  - name: gitops_server_address
    value: https://gitlab.ho-test.com
  - name: gitops_repository_name
    value: gitops-tap
  - name: gitops_repository_owner
    value: shjeon
  - name: gitops_branch
    value: dev
  - name: gitops_user_name
    value: shjeon
  - name: gitops_user_email
    value: shjeon@openbase.co.kr
  - name: gitops_commit_message
    value: test_giops
  - name: gitops_ssh_secret
    value: git-https
  - name: gitops_server_kind
    value: gitlab
  - name: gitops_commit_branch
    value: staging
  - name: gitops_pull_request_title
    value: ready for review
  - name: gitops_pull_request_body
    value: generated by supply chain
  - name: debug
    value: "true"
  - name: clusterBuilder
    value: default
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
  source:
    git:
      ref:
        branch: dev
      url: https://gitlab.ho-test.com/shjeon/tanzu-java-web-app.git
